### ISSUE TITLE
TODO: feature list plan & implementation

### ISSUE THREAD

**Issue by yuqingc** [yuqingc/rmdashrf#1]
- [ ] List file and/or directory of a specified directory

- [ ] Create file, directory

- [ ] Remove file, directory

- [ ] Copy file, directory

- [ ] Move file, directory

- [ ] Rename file, directory

- [ ] Upload file, directory

- [ ] Download file

- [ ] Download directory as an archived tar
